version: '3'

services:

  db-postgre:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: four_angle
    volumes:
      - ./container/postgres/data:/var/lib/postgresql/data