spring:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/four_angle
  flyway:
    enabled: false
    out-of-order: true

server:
  port: 8181

access-control-allow-origin: "*"

jwt:
  token:
    issuer: 4ANGLE
    signing-key: KEYMUSTBEHERE