spring:
  profiles:
    active: local
  jpa:
    database: postgresql
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      write-dates-as-timestamps: false
  flyway:
    enabled: false
    out-of-order: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,application/javascript,text/html,text/xml,text/plain




